app/views.py
# app/views.py
from fastapi.responses import FileResponse
from flask import Blueprint, Response, flash, make_response, render_template, request, redirect, url_for
# import pdfkit 
import random
import string
from io import BytesIO
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import mm, inch
from reportlab.pdfgen import canvas
from reportlab.platypus import Image, Paragraph, Table, TableStyle, PageBreak
from reportlab.lib import colors
from reportlab.lib.enums import TA_JUSTIFY, TA_LEFT, TA_CENTER, TA_RIGHT
from reportlab.lib.styles import ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, PageBreak, Spacer
from reportlab.platypus import Table
from reportlab.platypus import Image
from reportlab.platypus import TableStyle
from reportlab.lib import colors
from reportlab.lib.units import inch
from datetime import datetime
from datetime import time
from .models import Cooperativa
from .models import Unidad
from .models import Conductor
from .models import Usuario
from .models import Ciudad
from .models import Cliente
from .models import Ruta
from .models import Horario
from .models import Boleto
from .models import Pago
from .models import Itinerario
from .models import Comentario
from .models import Calificacion
from .models import Categoria_cliente
from .models import CabFactura
from .models import DetalleFactura
from .models import metodopago
from .models import Anden
from .models import Producto
from .models import Establecimiento
from .models import PuntoDeEmision
from sqlalchemy.orm import joinedload

from . import db

main_bp = Blueprint('main', __name__)

#-----------------------------------------------------------------------------------------------------------------

@main_bp.route('/')
def index():
    mostrar_contenido = True
    return render_template('index.html',mostrar_contenido=mostrar_contenido)


@main_bp.route('/ciudad/list')
def list_ciudades():
    ciudades = Ciudad.query.filter(Ciudad.estado != 0).all()
    return render_template('ciudad/list_ciudad.html', ciudades=ciudades)

@main_bp.route('/ciudad/add', methods=['GET', 'POST'])
def crear_ciudad():
    if request.method == 'POST':
        nombre = request.form['nombre']
        estado = 1
        ciudad = Ciudad(nombre=nombre, estado=estado)
        db.session.add(ciudad)
        db.session.commit()
        return redirect(url_for('main.list_ciudades'))
    return render_template('ciudad/add_ciudad.html')

@main_bp.route('/editar/<int:id>', methods=['GET', 'POST'])
def editar_ciudad(id):
    ciudad = Ciudad.query.get_or_404(id)
    if request.method == 'POST':
        ciudad.nombre = request.form['nombre']
        ciudad.estado = 1
        db.session.commit()
        return redirect(url_for('main.list_ciudades'))
    return render_template('ciudad/edit_ciudad.html', ciudad=ciudad)

@main_bp.route('/eliminar/<int:id>', methods=['POST'])
def eliminar_ciudad(id):
    ciudades = Ciudad.query.get(id)
    if ciudades:
        ciudades.estado = 0    
    
    db.session.commit()
    return redirect(url_for('main.list_ciudades'))

#-----------------------------------------------------------------------------------------------------------------

#Lista de usuarios
@main_bp.route('/user/list' , methods=['GET'])
def list_user():
    users = Usuario.query.filter(Usuario.estado != 0).all()
    return render_template('user/list_users.html', users=users)

#Nuevo usuarios
@main_bp.route('/user/add', methods=['GET', 'POST'])
def add_user():
    if request.method == 'POST':
        user = request.form['user']
        nombre = request.form['nombre']
        apellido = request.form['apellido']
        contraseña = request.form['pass']
        id_cooperativa = int(request.form['id_cooperativa'])
        usuariocreacion = "root"
        fechacreacion = datetime.now()
        estado  = 1
        
        if id_cooperativa is None:
            user = Usuario(user=user, nombre=nombre,apellido=apellido, contraseña=contraseña, usuariocreacion=usuariocreacion, fechacreacion=fechacreacion, estado=estado)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('main.list_user'))
        else:
            user = Usuario(user=user, nombre=nombre, id_cooperativa=id_cooperativa,apellido=apellido, contraseña=contraseña, usuariocreacion=usuariocreacion, fechacreacion=fechacreacion, estado=estado)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('main.list_user'))
    cooperativas = Cooperativa.query.filter(Cooperativa.estado != 0).all()
    return render_template('user/add_user.html',cooperativas=cooperativas)

#Editar usuarios
@main_bp.route('/user/<int:id>/edit', methods=['GET', 'POST'])
def edit_user(id):
    user = Usuario.query.get_or_404(id)
    if request.method == 'POST':
        user.user = request.form['user']
        user.nombre = request.form['nombre']
        user.apellido = request.form['apellido']
        user.contraseña = request.form['pass']
        user.id_cooperativa = request.form['id_cooperativa']
        db.session.commit()
        return redirect(url_for('main.list_user'))
    cooperativas = Cooperativa.query.filter(Cooperativa.estado != 0).all()
    return render_template('user/edit_user.html', user=user,cooperativas=cooperativas)

#Eliminar usuarios
@main_bp.route('/user/<int:id>/delete', methods=['POST'])
def delete_user(id):
    users = Usuario.query.get(id)
    if users: 
        users.estado = 0  # Cambiar el estado a '0'
        db.session.commit()
        flash('Usuario eliminado exitosamente.')

    return redirect(url_for('main.list_user'))

#-----------------------------------------------------------------------------------------------------------------

#Eliminar/Inactivar cliente
@main_bp.route('/client/<int:id>', methods=['POST'])
def delete_client(id):
    cliente = Cliente.query.get(id)
    if cliente:
        cliente.estado_cliente = 0  # Cambiar el estado a '0'
        db.session.commit()
    return redirect(url_for('main.list_clients'))  # Redirigir a una página de lista de clientes

#Editar clientes
@main_bp.route('/client/<int:id>/edit', methods=['GET', 'POST'])
def edit_client(id):
    clientes = Cliente.query.get_or_404(id)
    if request.method == 'POST':
        clientes.nombre_cliente = request.form['nombre']
        clientes.apellido_cliente = request.form['apellido']
        clientes.cedula = request.form['cedula']
        clientes.email = request.form['email']
        clientes.fecha_nacimiento = request.form['fecha_nacimiento']
        clientes.direccion = request.form['direccion']
        clientes.telefono = request.form['telefono']
        clientes.cod_postal = request.form['cod_postal']
        db.session.commit()
        return redirect(url_for('main.list_clients'))
    return render_template('cliente/edit_client.html', clientes=clientes)

#Lista clientes
@main_bp.route('/client/list' , methods=['GET'])
def list_clients():
    clientes =  Cliente.query.filter(Cliente.estado_cliente != 0).all()
    return render_template('cliente/list_clients.html', clientes=clientes)

#Nuevo clientes
@main_bp.route('/client/add', methods=['GET', 'POST'])
def add_client():
    if request.method == 'POST':
        nombre_cliente = request.form['nombre']
        apellido_cliente = request.form['apellido']
        cedula = request.form['cedula']
        email = request.form['email']
        fecha_nacimiento = request.form['fecha_nacimiento']
        direccion = request.form['direccion']
        telefono = request.form['telefono']
        cod_postal = request.form['cod_postal']
        fecha_registro = datetime.now()
        ciudad = request.form['ciudad']
        estado_cliente = 1
        fecha_nacimientostr = datetime.strptime(fecha_nacimiento, '%Y-%m-%d').date()
        client = Cliente(nombre_cliente=nombre_cliente, apellido_cliente=apellido_cliente, cedula=cedula, estado_cliente=estado_cliente,email=email,fecha_nacimiento=fecha_nacimientostr,telefono=telefono,direccion=direccion,cod_postal=cod_postal,fecha_registro=fecha_registro,ciudad=ciudad)
        db.session.add(client)
        db.session.commit()
        flash("cliente creado exitosamente")
        return redirect(url_for('main.list_clients'))
    ciudades = Ciudad.query.all()
    return render_template('cliente/add_client.html',ciudades=ciudades)

#----------------------------------------------------------------------------------------------------------------------------------------------------------------------------

# Lista unidades
@main_bp.route('/unidad/list' , methods=['GET', 'POST'])
def list_unidades():
    if request.method == 'POST':
        modelo = request.form.get('modelo')
        query = Unidad.query
        if modelo:
            query = query.filter(Unidad.modelo.like(f"%{modelo}%"))

        unidades = query.all()
    else:
        unidades = Unidad.query.filter_by(estado=1)
    #unidades = Unidad.query.filter(Unidad.estado != 0).all()
    return render_template('unidad/list_unidades.html', unidades=unidades)

# Reporte de unidades / buses
@main_bp.route('/report_unidades',methods=['POST'])
def report_unidad():

    outputIoStream = BytesIO()

    pdf = SimpleDocTemplate(
        outputIoStream,
        page_size=A4,
        rightMargin=12,
        leftMargin=12,
        topMargin=12,
        bottomMargin=18,
        showBoundary=True,
        )
# define estilo de tablas
    table_style = TableStyle(
            [
                ("GRID", (0, 0), (-1, -1), 0, colors.black),
                ("BOX", (0, 0), (-1, -1), 0, colors.black),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("ALIGN", (0, 0), (-1, -1), "RIGHT"),
                ("TOPPADDING", (0, 0), (-1, -1), 0),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
                ("LEFTPADDING", (0, 0), (-1, -1), 0),
                ("FONTSIZE", (0, 0), (-1, -1), 11),

app/templates/cliente/add_client.html
<!-- app/templates/add_product.html -->


{% extends 'index.html' %} {% with messages = get_flashed_messages() %}
{% if messages %}
    <ul>
        {% for message in messages %}
            <li>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
{% endwith %} {% block content %}
<!--Titulo-->
<h1 class="text-primary">Nuevo cliente</h1>
<!--Menu-->
<!--Formulario de ingreso de clientes-->
<form action="{{ url_for('main.add_client') }}" method="post">
    <nav class="navbar navbar-expand-lg navbar-light ">
        <div class="container-fluid">
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                
              </li>
              <li class="nav-item">
                
              </li>
            </ul>
          </div>
        </div>
      </nav>

      <div class="form-floating mb-3">
        <input class="form-control" type="text" id="nombre" name="nombre" required>
        <label for="nombre">Nombre:</label>
    </div>
    
    <div class="form-floating mb-3">
        <input class="form-control" type="text" id="apellido" name="apellido" required>
        <label for="apellido">Apellido:</label>
    </div>
    
    <div class="form-floating mb-3">
        <input class="form-control" type="text" id="cedula" name="cedula" required>
        <label for="cedula">Cédula:</label>
    </div>
    
    <div class="form-floating mb-3">
        <input class="form-control" type="email" id="email" name="email" required>
        <label for="email">Email:</label>
    </div>
    
    <div class="form-floating mb-3">
        <input class="form-control" type="date" id="fecha_nacimiento" name="fecha_nacimiento" required>
        <label for="fecha_nacimiento">Fecha de Nacimiento:</label>
    </div>
    
    <div class="form-floating mb-3">
        <input class="form-control" type="text" id="direccion" name="direccion" required>
        <label for="direccion">Dirección:</label>
    </div>
    
    <div class="form-floating mb-3">
        <input class="form-control" type="text" id="telefono" name="telefono" required>
        <label for="telefono">Teléfono:</label>
    </div>
    <div class="form-floating mb-3">
      
      <select id="ciudad" name="ciudad" class="form-control" required>
        {% for ciudad in ciudades %}
          <option value="{{ ciudad.id_ciudad }}">{{ ciudad.nombre }}</option>
          {% endfor %}
      </select>
      <label for="ciudad">ciudad:</label>
  </div>
    
    <div class="form-floating mb-3">
        <input class="form-control" type="text" id="cod_postal" name="cod_postal" required>
        <label for="cod_postal">Código Postal:</label>
    </div>
    <button type="submit" class="nav-item border-1 btn btn-success me-3 text-light fw-bold">&#129485;Guardar</button>
    <a href="#" class="nav-item border-1 btn btn-dark me-3 text-light fw-bold">&#128196;Reporte</a>
</form>
{% endblock %}

app/templates/cliente/edit_client.html
<!-- app/templates/edit_product.html -->
{% extends 'index.html' %}
{% with messages = get_flashed_messages() %}
{% if messages %}
    <ul>
        {% for message in messages %}
            <li>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
{% endwith %}

{% block content %}
<!--Formulario de edicion de clientes-->
<div class="container px-5 my-5">
    <div class="row justify-content-center">
        <div class="col-lg-8">
            <div class="card border-0 rounded-3 shadow-lg">
                <div class="card-body p-4">
                    <div class="text-center">
                        <div class="h1 fw-light">Editar Cliente</div>
                        <p class="mb-4 text-muted">Modificar el cliente.</p>
                    </div>
                    <form action="{{ url_for('main.edit_client', id=clientes.id_cliente) }}"  method="post">

                      <!-- Nombre Input -->
    <div class="form-floating mb-3">
        <input class="form-control" type="text" id="nombre" name="nombre" value="{{ clientes.nombre_cliente }}" required>
        <label for="nombre">Nombre:</label>
    </div>
    
    <!-- Apellidos Input -->
    <div class="form-floating mb-3">
        <input class="form-control" type="text" id="apellido" name="apellido" value="{{ clientes.apellido_cliente }}" required>
        <label for="apellido">Apellido:</label>
    </div>
    
    <!-- Cédula Input -->
    <div class="form-floating mb-3">
        <input class="form-control" type="text" id="cedula" name="cedula" value="{{ clientes.cedula }}" required>
        <label for="cedula">Cédula:</label>
    </div>
    
    <!-- Email Input -->
    <div class="form-floating mb-3">
        <input class="form-control" type="email" id="email" name="email" value="{{ clientes.email }}" required>
        <label for="email">Email:</label>
    </div>
    
    <!-- Fecha de Nacimiento Input -->
    <div class="form-floating mb-3">
        <input class="form-control" type="date" id="fecha_nacimiento" name="fecha_nacimiento" value="{{ clientes.fecha_nacimiento.strftime('%Y-%m-%d') }}" required>
        <label for="fecha_nacimiento">Fecha de Nacimiento:</label>
    </div>
    
    <!-- Dirección Input -->
    <div class="form-floating mb-3">
        <input class="form-control" type="text" id="direccion" name="direccion" value="{{ clientes.direccion }}" required>
        <label for="direccion">Dirección:</label>
    </div>
    
    <!-- Teléfono Input -->
    <div class="form-floating mb-3">
        <input class="form-control" type="text" id="telefono" name="telefono" value="{{ clientes.telefono }}" required>
        <label for="telefono">Teléfono:</label>
    </div>
    
    <!-- Código Postal Input -->
    <div class="form-floating mb-3">
        <input class="form-control" type="text" id="cod_postal" name="cod_postal" value="{{ clientes.cod_postal }}" required>
        <label for="cod_postal">Código Postal:</label>
    </div>
                        <!-- Submit success message -->
                        <div class="d-none" id="submitSuccessMessage">
                            <div class="text-center mb-3">
                                <div class="fw-bolder">Form submission successful!</div>
                                <p>To activate this form, sign up at</p>
                                <a
                                    href="https://startbootstrap.com/solution/contact-forms">https://startbootstrap.com/solution/contact-forms</a>
                            </div>
                        </div>

                        <!-- Submit error message -->
                        <div class="d-none" id="submitErrorMessage">
                            <div class="text-center text-danger mb-3">Error sending message!</div>
                        </div>

                        <!-- Guardar Cliente -->
                        <div class="d-grid">
                            <button class="btn btn-primary" type="submit">Modificar Cliente</button>
                        </div>
                    </form>
                    <!-- Fin formulario -->
                </div>
            </div>
        </div>
    </div>
</div>
<a href="{{ url_for('main.list_clients') }}">Back to Clientes List</a>
{% endblock %}

app/templates/cliente/list_clients.html
{% extends 'index.html' %} {% with messages = get_flashed_messages() %}
{% if messages %}
    <ul>
        {% for message in messages %}
            <li>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
{% endwith %}  {% block content %}
<!-- Barra de navegación -->
<div>
  <div class="h1 fw-light text-primary">Nuevo cliente</div>
</div>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a
            class="nav-link btn btn-success text-light fw-bold me-3"
            aria-current="page"
            href="{{ url_for('main.add_client') }}"
            >&#129485;Nuevo cliente</a
          >
        </li>
        <li class="nav-item">
          <a class="nav-link btn btn-dark text-light fw-bold" href="#">&#128196;Reporte</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
<!--Cabecera de tabla de creacion de clientes-->
<div class="container mt-5">
  <table class="table table-striped table-hover">
    <thead class="table-light">
      <tr>
        <th scope="col">Nombre</th>
        <th scope="col">Apellido</th>
        <th style="with:10%;" scope="col">Identificacion</th>
        <th scope="col">Ciudad</th>
        <th scope="col">Email</th>
      </tr>
      <!--Filtro para campos-->
      <tr>
        <th>
          <input
            type="text"
            class="filter-input"
            id="filterNombre"
            placeholder="Filtrar Nombre"
          />
        </th>
        <th>
          <input
            type="text"
            class="filter-input"
            id="filterApellido"
            placeholder="Filtrar Apellido"
          />
        </th>
        <th style="with:10%;">
          <input
            type="text"
            class="filter-input"
            id="filterIdentificacion"
            placeholder="Filtrar Identificacion"
          />
        </th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for cliente in clientes %}
      <tr>
        <td>{{ cliente.nombre_cliente }}</td>
        <td>{{ cliente.apellido_cliente }}</td>
        <td>{{ cliente.cedula }}</td>
        <td>{{ cliente.ciudad_ref.nombre }}</td>
        <td>{{ cliente.email }}</td>
        <td>
          <a
            class="btn btn-primary"
            href="{{ url_for('main.edit_client', id=cliente.id_cliente) }}">Editar</a>
        </td>
        <td>
          <form action="{{ url_for('main.delete_client', id=cliente.id_cliente) }}"
            method="post">
            <button class="btn btn-danger" type="submit">Eliminar</button>
          </form>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}