app/views.py
# app/views.py
from fastapi.responses import FileResponse
from flask import Blueprint, Response, flash, make_response, render_template, request, redirect, url_for
# import pdfkit 
import random
import string
from io import BytesIO
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import mm, inch
from reportlab.pdfgen import canvas
from reportlab.platypus import Image, Paragraph, Table, TableStyle, PageBreak
from reportlab.lib import colors
from reportlab.lib.enums import TA_JUSTIFY, TA_LEFT, TA_CENTER, TA_RIGHT
from reportlab.lib.styles import ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, PageBreak, Spacer
from reportlab.platypus import Table
from reportlab.platypus import Image
from reportlab.platypus import TableStyle
from reportlab.lib import colors
from reportlab.lib.units import inch
from datetime import datetime
from datetime import time
from .models import Cooperativa
from .models import Unidad
from .models import Conductor
from .models import Usuario
from .models import Ciudad
from .models import Cliente
from .models import Ruta
from .models import Horario
from .models import Boleto
from .models import Pago
from .models import Itinerario
from .models import Comentario
from .models import Calificacion
from .models import Categoria_cliente
from .models import CabFactura
from .models import DetalleFactura
from .models import metodopago
from .models import Anden
from .models import Producto
from .models import Establecimiento
from .models import PuntoDeEmision
from sqlalchemy.orm import joinedload

from . import db

main_bp = Blueprint('main', __name__)

#-----------------------------------------------------------------------------------------------------------------

@main_bp.route('/')
def index():
    mostrar_contenido = True
    return render_template('index.html',mostrar_contenido=mostrar_contenido)


@main_bp.route('/ciudad/list')
def list_ciudades():
    ciudades = Ciudad.query.filter(Ciudad.estado != 0).all()
    return render_template('ciudad/list_ciudad.html', ciudades=ciudades)

@main_bp.route('/ciudad/add', methods=['GET', 'POST'])
def crear_ciudad():
    if request.method == 'POST':
        nombre = request.form['nombre']
        estado = 1
        ciudad = Ciudad(nombre=nombre, estado=estado)
        db.session.add(ciudad)
        db.session.commit()
        return redirect(url_for('main.list_ciudades'))
    return render_template('ciudad/add_ciudad.html')

@main_bp.route('/editar/<int:id>', methods=['GET', 'POST'])
def editar_ciudad(id):
    ciudad = Ciudad.query.get_or_404(id)
    if request.method == 'POST':
        ciudad.nombre = request.form['nombre']
        ciudad.estado = 1
        db.session.commit()
        return redirect(url_for('main.list_ciudades'))
    return render_template('ciudad/edit_ciudad.html', ciudad=ciudad)

@main_bp.route('/eliminar/<int:id>', methods=['POST'])
def eliminar_ciudad(id):
    ciudades = Ciudad.query.get(id)
    if ciudades:
        ciudades.estado = 0    
    
    db.session.commit()
    return redirect(url_for('main.list_ciudades'))

#-----------------------------------------------------------------------------------------------------------------

#Lista de usuarios
@main_bp.route('/user/list' , methods=['GET'])
def list_user():
    users = Usuario.query.filter(Usuario.estado != 0).all()
    return render_template('user/list_users.html', users=users)

#Nuevo usuarios
@main_bp.route('/user/add', methods=['GET', 'POST'])
def add_user():
    if request.method == 'POST':
        user = request.form['user']
        nombre = request.form['nombre']
        apellido = request.form['apellido']
        contraseña = request.form['pass']
        id_cooperativa = int(request.form['id_cooperativa'])
        usuariocreacion = "root"
        fechacreacion = datetime.now()
        estado  = 1
        
        if id_cooperativa is None:
            user = Usuario(user=user, nombre=nombre,apellido=apellido, contraseña=contraseña, usuariocreacion=usuariocreacion, fechacreacion=fechacreacion, estado=estado)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('main.list_user'))
        else:
            user = Usuario(user=user, nombre=nombre, id_cooperativa=id_cooperativa,apellido=apellido, contraseña=contraseña, usuariocreacion=usuariocreacion, fechacreacion=fechacreacion, estado=estado)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('main.list_user'))
    cooperativas = Cooperativa.query.filter(Cooperativa.estado != 0).all()
    return render_template('user/add_user.html',cooperativas=cooperativas)

#Editar usuarios
@main_bp.route('/user/<int:id>/edit', methods=['GET', 'POST'])
def edit_user(id):
    user = Usuario.query.get_or_404(id)
    if request.method == 'POST':
        user.user = request.form['user']
        user.nombre = request.form['nombre']
        user.apellido = request.form['apellido']
        user.contraseña = request.form['pass']
        user.id_cooperativa = request.form['id_cooperativa']
        db.session.commit()
        return redirect(url_for('main.list_user'))
    cooperativas = Cooperativa.query.filter(Cooperativa.estado != 0).all()
    return render_template('user/edit_user.html', user=user,cooperativas=cooperativas)

#Eliminar usuarios
@main_bp.route('/user/<int:id>/delete', methods=['POST'])
def delete_user(id):
    users = Usuario.query.get(id)
    if users: 
        users.estado = 0  # Cambiar el estado a '0'
        db.session.commit()
        flash('Usuario eliminado exitosamente.')

    return redirect(url_for('main.list_user'))

#-----------------------------------------------------------------------------------------------------------------

#Eliminar/Inactivar cliente
@main_bp.route('/client/<int:id>', methods=['POST'])
def delete_client(id):
    cliente = Cliente.query.get(id)
    if cliente:
        cliente.estado_cliente = 0  # Cambiar el estado a '0'
        db.session.commit()
    return redirect(url_for('main.list_clients'))  # Redirigir a una página de lista de clientes

#Editar clientes
@main_bp.route('/client/<int:id>/edit', methods=['GET', 'POST'])
def edit_client(id):
    clientes = Cliente.query.get_or_404(id)
    if request.method == 'POST':
        clientes.nombre_cliente = request.form['nombre']
        clientes.apellido_cliente = request.form['apellido']
        clientes.cedula = request.form['cedula']
        clientes.email = request.form['email']
        clientes.fecha_nacimiento = request.form['fecha_nacimiento']
        clientes.direccion = request.form['direccion']
        clientes.telefono = request.form['telefono']
        clientes.cod_postal = request.form['cod_postal']
        db.session.commit()
        return redirect(url_for('main.list_clients'))
    return render_template('cliente/edit_client.html', clientes=clientes)

#Lista clientes
@main_bp.route('/client/list' , methods=['GET'])
def list_clients():
    clientes =  Cliente.query.filter(Cliente.estado_cliente != 0).all()
    return render_template('cliente/list_clients.html', clientes=clientes)

#Nuevo clientes
@main_bp.route('/client/add', methods=['GET', 'POST'])
def add_client():
    if request.method == 'POST':
        nombre_cliente = request.form['nombre']
        apellido_cliente = request.form['apellido']
        cedula = request.form['cedula']
        email = request.form['email']
        fecha_nacimiento = request.form['fecha_nacimiento']
        direccion = request.form['direccion']
        telefono = request.form['telefono']
        cod_postal = request.form['cod_postal']
        fecha_registro = datetime.now()
        ciudad = request.form['ciudad']
        estado_cliente = 1
        fecha_nacimientostr = datetime.strptime(fecha_nacimiento, '%Y-%m-%d').date()
        client = Cliente(nombre_cliente=nombre_cliente, apellido_cliente=apellido_cliente, cedula=cedula, estado_cliente=estado_cliente,email=email,fecha_nacimiento=fecha_nacimientostr,telefono=telefono,direccion=direccion,cod_postal=cod_postal,fecha_registro=fecha_registro,ciudad=ciudad)
        db.session.add(client)
        db.session.commit()
        flash("cliente creado exitosamente")
        return redirect(url_for('main.list_clients'))
    ciudades = Ciudad.query.all()
    return render_template('cliente/add_client.html',ciudades=ciudades)

#----------------------------------------------------------------------------------------------------------------------------------------------------------------------------

# Lista unidades
@main_bp.route('/unidad/list' , methods=['GET', 'POST'])
def list_unidades():
    if request.method == 'POST':
        modelo = request.form.get('modelo')
        query = Unidad.query
        if modelo:
            query = query.filter(Unidad.modelo.like(f"%{modelo}%"))

        unidades = query.all()
    else:
        unidades = Unidad.query.filter_by(estado=1)
    #unidades = Unidad.query.filter(Unidad.estado != 0).all()
    return render_template('unidad/list_unidades.html', unidades=unidades)

# Reporte de unidades / buses
@main_bp.route('/report_unidades',methods=['POST'])
def report_unidad():

    outputIoStream = BytesIO()

    pdf = SimpleDocTemplate(
        outputIoStream,
        page_size=A4,
        rightMargin=12,
        leftMargin=12,
        topMargin=12,
        bottomMargin=18,
        showBoundary=True,
        )
# define estilo de tablas
    table_style = TableStyle(
            [
                ("GRID", (0, 0), (-1, -1), 0, colors.black),
                ("BOX", (0, 0), (-1, -1), 0, colors.black),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("ALIGN", (0, 0), (-1, -1), "RIGHT"),
                ("TOPPADDING", (0, 0), (-1, -1), 0),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
                ("LEFTPADDING", (0, 0), (-1, -1), 0),
                ("FONTSIZE", (0, 0), (-1, -1), 11),

app/templates/unidad/add_unidades.html
<!-- app/templates/add_product.html -->
{% extends 'index.html' %}

{% block content %}


    <div class="container mt-5">
        <h1>Registrar una unidad de bus</h1>
        <form action="{{ url_for('main.add_unidad') }}" method="post">
   
            <div class="form-group">
                <label for="id_cooperativa">Cooperativa:</label>
                <select id="id_cooperativa" name="id_cooperativa" class="form-control" required>
                    {% for cooperativa in cooperativas %}
                    <option selected>Seleccione una razon social</option>
                    <option value="{{ cooperativa.id_cooperativa }}">{{ cooperativa.razonsocial }}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="form-group">
                <label for="id_conductor">Conductor:</label>
                <select id="id_conductor" name="id_conductor" class="form-control" required>
                    {% for conductor in conductores %}
                    <option selected>Seleccione un conductor</option>
                    <option value="{{ conductor.id }} "> {{ conductor.nombre }}  {{ conductor.apellido }}</option>
                    {% endfor %}
                </select>
            </div>
      
            <div class="form-group">
                <label for="placa">Placa:</label>
                <input type="text" id="placa" name="placa" class="form-control" required>
            </div>
            <div class="form-group">
                <label for="modelo">Modelo:</label>
                <input type="text" id="modelo" name="modelo" class="form-control" required>
            </div>
            <div class="form-group">
                <label for="ano">Año:</label>
                <input type="number" id="ano" name="ano" class="form-control" required>
            </div>
            <div class="form-group">
                <label for="nro_disco">Número de Disco:</label>
                <input type="number" id="nro_disco" name="nro_disco" class="form-control" required>
            </div>
            <div class="form-group">
                <label for="nrodeasientos">Número de Asientos:</label>
                <input type="number" id="nrodeasientos" name="nrodeasientos" class="form-control" required>
            </div>
            <br>
            <button type="submit" class="btn btn-success">Guardar</button>
        </form>
        <a href="{{ url_for('main.list_unidades') }}" class="btn btn-secondary mt-3">Volver a la Lista de unidades</a>
    </div>
    <script src="{{ url_for('static', filename='dist/js/bootstrap.min.js') }}"></script>



{% endblock %}

app/templates/unidad/edit_unidades.html
<!-- app/templates/edit_product.html -->
{% extends 'index.html' %}

{% block content %}
    <h1>Modificar Unidad </h1>

    <form id="editForm" action="{{ url_for('main.edit_unidad', id=unidades.id_unidad) }}" method="post"> 
        <!-- 2 column grid layout with text inputs for the first and last names -->
        <div class="row mb-4">
          <label for="id_conductor">Conductor:</label>
          <select id="id_conductor" name="id_conductor" class="form-control" required>
              {% for conductor in conductores %}
              <option value="{{ conductor.id }}">{{ conductor.nombre }}  {{ conductor.apellido }}</option>
              {% endfor %}
          </select>
      </div>
      <div class="row mb-4">
      <label for="id_cooperativa">Cooperativa:</label>
      <select id="id_cooperativa" name="id_cooperativa" class="form-control" required>
          {% for cooperativa in cooperativas %}
          <option value="{{ cooperativa.id_cooperativa }}">{{ cooperativa.razonsocial }} </option>
          {% endfor %}
      </select>
  </div>

        <div class="row mb-4">
          <div class="col">
              <div data-mdb-input-init class="form-outline">
                  <label class="form-label" for="placa">Placa:</label>
                  <input type="text" class="form-control" id="placa" name="placa" value="{{ unidades.placa }}" required />
              </div>
          </div>
          <div class="col">
              <div data-mdb-input-init class="form-outline">
                  <label class="form-label" for="modelo">Modelo:</label>
                  <input type="text" class="form-control" id="modelo" name="modelo" value="{{ unidades.modelo }}" required />
              </div>
          </div>
      </div>
      <div class="row mb-4">
          <div class="col">
              <div data-mdb-input-init class="form-outline">
                  <label class="form-label" for="ano">Año:</label>
                  <input type="number" class="form-control" id="ano" name="ano" value="{{ unidades.ano }}" required />
              </div>
          </div>
          <div class="col">
              <div data-mdb-input-init class="form-outline">
                  <label class="form-label" for="nro_disco">Número de Disco:</label>
                  <input type="number" class="form-control" id="nro_disco" name="nro_disco" value="{{ unidades.nro_disco }}" required />
              </div>
          </div>
      </div>
      <div class="row mb-4">
          <div class="col">
              <div data-mdb-input-init class="form-outline">
                  <label class="form-label" for="nrodeasientos">Número de Asientos:</label>
                  <input type="number" class="form-control" id="nrodeasientos" name="nrodeasientos" value="{{ unidades.nrodeasientos }}" required />
              </div>
          </div>
      </div>
     
        <!-- Submit button -->
        <button class="btn btn-success"  type="submit">Modificar</button>
        <a class="btn btn-dark"  href="{{ url_for('main.list_unidades') }}">Regresar a lista Buses </a>
      </form>
 {% endblock %} 


 

app/templates/unidad/list_unidades.html
{% extends 'index.html' %} {% block content %}
<!-- Barra de navegación -->
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}"/>

<div>
  <div class="h1 fw-light text-primary">Lista de unidades / buses</div>
</div>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <div class="" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link btn btn-success text-light fw-bold me-3" aria-current="page" href="{{ url_for('main.add_unidad') }}">&#129485;Nueva Unidad</a>
        </li>
        <li class="nav-item">
          <form action="{{ url_for('main.report_unidad') }}" method="post">
            <button type="submit" class="nav-link btn btn-dark fw-bold text-light">&#128196;Reporte</button>
          </form>
        </li>
      </ul>
    </div>
  </div>
</nav>
<form action="{{ url_for('main.list_unidades') }}" method="post">
  <label for="nombre">Nombre conductor:</label>
  <input type="text" id="modelo" name="modelo" required>
  <input type="hidden" id="buscar" name="buscar" value="buscar">
  <button type="submit" id="buscar" name="buscar" value="buscar">Buscar
  </button>
</form>

<!--Cabecera de tabla de creacion de buses-->
<div class="container mt-5">
  <table class="table table-dark table-striped">
    <thead class="table-light text-center text-primary">
      <tr>
        <th scope="col">Nombre cooperativa</th>
        <th scope="col">Nombre conductor</th>
        <th scope="col">modelo</th>
        <th scope="col">año</th>
        <th scope="col">placa</th>
        <th scope="col">N° disco</th>
        <th scope="col">N° asientos</th>
        <td scope="col">Editar</td>
        <td scope="col">Eliminar</td>
      </tr>
      <!--Filtro para campos
      <tr>
        <th>
          <input type="text" class="filter-input tamano-4" id="filterNombre" placeholder="Filtrar Nombre conductor"/>
        </th>
      </tr>-->
    </thead>
    <tbody>
      {% for unidad in unidades %}

      <tr>
        <td>{{unidad.unidad_cooperativa.razonsocial}}</td>
        <td>{{ unidad.conductor.nombre }} {{ unidad.conductor.apellido }}</td>
        <td>{{unidad.modelo}}</td>
        <td>{{unidad.ano}}</td>
        <td>{{unidad.placa}}</td>
        <td>{{unidad.nro_disco}}</td>
        <td>{{unidad.nrodeasientos}}</td>
        <td>
          <a
            class="btn btn-primary"
            href="{{ url_for('main.edit_unidad', id=unidad.id_unidad) }}"
            >Editar</a
          >
        </td>
        <td>
          <form
            action="{{ url_for('main.delete_unidad', id=unidad.id_unidad) }}"
            method="post"
          >
            <button class="btn btn-danger" type="submit">Eliminar</button>
          </form>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}