app/views.py
# app/views.py
from fastapi.responses import FileResponse
from flask import Blueprint, Response, flash, make_response, render_template, request, redirect, url_for
# import pdfkit 
import random
import string
from io import BytesIO
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import mm, inch
from reportlab.pdfgen import canvas
from reportlab.platypus import Image, Paragraph, Table, TableStyle, PageBreak
from reportlab.lib import colors
from reportlab.lib.enums import TA_JUSTIFY, TA_LEFT, TA_CENTER, TA_RIGHT
from reportlab.lib.styles import ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, PageBreak, Spacer
from reportlab.platypus import Table
from reportlab.platypus import Image
from reportlab.platypus import TableStyle
from reportlab.lib import colors
from reportlab.lib.units import inch
from datetime import datetime
from datetime import time
from .models import Cooperativa
from .models import Unidad
from .models import Conductor
from .models import Usuario
from .models import Ciudad
from .models import Cliente
from .models import Ruta
from .models import Horario
from .models import Boleto
from .models import Pago
from .models import Itinerario
from .models import Comentario
from .models import Calificacion
from .models import Categoria_cliente
from .models import CabFactura
from .models import DetalleFactura
from .models import metodopago
from .models import Anden
from .models import Producto
from .models import Establecimiento
from .models import PuntoDeEmision
from sqlalchemy.orm import joinedload

from . import db

main_bp = Blueprint('main', __name__)

#-----------------------------------------------------------------------------------------------------------------

@main_bp.route('/')
def index():
    mostrar_contenido = True
    return render_template('index.html',mostrar_contenido=mostrar_contenido)


@main_bp.route('/ciudad/list')
def list_ciudades():
    ciudades = Ciudad.query.filter(Ciudad.estado != 0).all()
    return render_template('ciudad/list_ciudad.html', ciudades=ciudades)

@main_bp.route('/ciudad/add', methods=['GET', 'POST'])
def crear_ciudad():
    if request.method == 'POST':
        nombre = request.form['nombre']
        estado = 1
        ciudad = Ciudad(nombre=nombre, estado=estado)
        db.session.add(ciudad)
        db.session.commit()
        return redirect(url_for('main.list_ciudades'))
    return render_template('ciudad/add_ciudad.html')

@main_bp.route('/editar/<int:id>', methods=['GET', 'POST'])
def editar_ciudad(id):
    ciudad = Ciudad.query.get_or_404(id)
    if request.method == 'POST':
        ciudad.nombre = request.form['nombre']
        ciudad.estado = 1
        db.session.commit()
        return redirect(url_for('main.list_ciudades'))
    return render_template('ciudad/edit_ciudad.html', ciudad=ciudad)

@main_bp.route('/eliminar/<int:id>', methods=['POST'])
def eliminar_ciudad(id):
    ciudades = Ciudad.query.get(id)
    if ciudades:
        ciudades.estado = 0    
    
    db.session.commit()
    return redirect(url_for('main.list_ciudades'))

#-----------------------------------------------------------------------------------------------------------------

#Lista de usuarios
@main_bp.route('/user/list' , methods=['GET'])
def list_user():
    users = Usuario.query.filter(Usuario.estado != 0).all()
    return render_template('user/list_users.html', users=users)

#Nuevo usuarios
@main_bp.route('/user/add', methods=['GET', 'POST'])
def add_user():
    if request.method == 'POST':
        user = request.form['user']
        nombre = request.form['nombre']
        apellido = request.form['apellido']
        contraseña = request.form['pass']
        id_cooperativa = int(request.form['id_cooperativa'])
        usuariocreacion = "root"
        fechacreacion = datetime.now()
        estado  = 1
        
        if id_cooperativa is None:
            user = Usuario(user=user, nombre=nombre,apellido=apellido, contraseña=contraseña, usuariocreacion=usuariocreacion, fechacreacion=fechacreacion, estado=estado)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('main.list_user'))
        else:
            user = Usuario(user=user, nombre=nombre, id_cooperativa=id_cooperativa,apellido=apellido, contraseña=contraseña, usuariocreacion=usuariocreacion, fechacreacion=fechacreacion, estado=estado)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('main.list_user'))
    cooperativas = Cooperativa.query.filter(Cooperativa.estado != 0).all()
    return render_template('user/add_user.html',cooperativas=cooperativas)

#Editar usuarios
@main_bp.route('/user/<int:id>/edit', methods=['GET', 'POST'])
def edit_user(id):
    user = Usuario.query.get_or_404(id)
    if request.method == 'POST':
        user.user = request.form['user']
        user.nombre = request.form['nombre']
        user.apellido = request.form['apellido']
        user.contraseña = request.form['pass']
        user.id_cooperativa = request.form['id_cooperativa']
        db.session.commit()
        return redirect(url_for('main.list_user'))
    cooperativas = Cooperativa.query.filter(Cooperativa.estado != 0).all()
    return render_template('user/edit_user.html', user=user,cooperativas=cooperativas)

#Eliminar usuarios
@main_bp.route('/user/<int:id>/delete', methods=['POST'])
def delete_user(id):
    users = Usuario.query.get(id)
    if users: 
        users.estado = 0  # Cambiar el estado a '0'
        db.session.commit()
        flash('Usuario eliminado exitosamente.')

    return redirect(url_for('main.list_user'))

#-----------------------------------------------------------------------------------------------------------------

#Eliminar/Inactivar cliente
@main_bp.route('/client/<int:id>', methods=['POST'])
def delete_client(id):
    cliente = Cliente.query.get(id)
    if cliente:
        cliente.estado_cliente = 0  # Cambiar el estado a '0'
        db.session.commit()
    return redirect(url_for('main.list_clients'))  # Redirigir a una página de lista de clientes

#Editar clientes
@main_bp.route('/client/<int:id>/edit', methods=['GET', 'POST'])
def edit_client(id):
    clientes = Cliente.query.get_or_404(id)
    if request.method == 'POST':
        clientes.nombre_cliente = request.form['nombre']
        clientes.apellido_cliente = request.form['apellido']
        clientes.cedula = request.form['cedula']
        clientes.email = request.form['email']
        clientes.fecha_nacimiento = request.form['fecha_nacimiento']
        clientes.direccion = request.form['direccion']
        clientes.telefono = request.form['telefono']
        clientes.cod_postal = request.form['cod_postal']
        db.session.commit()
        return redirect(url_for('main.list_clients'))
    return render_template('cliente/edit_client.html', clientes=clientes)

#Lista clientes
@main_bp.route('/client/list' , methods=['GET'])
def list_clients():
    clientes =  Cliente.query.filter(Cliente.estado_cliente != 0).all()
    return render_template('cliente/list_clients.html', clientes=clientes)

#Nuevo clientes
@main_bp.route('/client/add', methods=['GET', 'POST'])
def add_client():
    if request.method == 'POST':
        nombre_cliente = request.form['nombre']
        apellido_cliente = request.form['apellido']
        cedula = request.form['cedula']
        email = request.form['email']
        fecha_nacimiento = request.form['fecha_nacimiento']
        direccion = request.form['direccion']
        telefono = request.form['telefono']
        cod_postal = request.form['cod_postal']
        fecha_registro = datetime.now()
        ciudad = request.form['ciudad']
        estado_cliente = 1
        fecha_nacimientostr = datetime.strptime(fecha_nacimiento, '%Y-%m-%d').date()
        client = Cliente(nombre_cliente=nombre_cliente, apellido_cliente=apellido_cliente, cedula=cedula, estado_cliente=estado_cliente,email=email,fecha_nacimiento=fecha_nacimientostr,telefono=telefono,direccion=direccion,cod_postal=cod_postal,fecha_registro=fecha_registro,ciudad=ciudad)
        db.session.add(client)
        db.session.commit()
        flash("cliente creado exitosamente")
        return redirect(url_for('main.list_clients'))
    ciudades = Ciudad.query.all()
    return render_template('cliente/add_client.html',ciudades=ciudades)

#----------------------------------------------------------------------------------------------------------------------------------------------------------------------------

# Lista unidades
@main_bp.route('/unidad/list' , methods=['GET', 'POST'])
def list_unidades():
    if request.method == 'POST':
        modelo = request.form.get('modelo')
        query = Unidad.query
        if modelo:
            query = query.filter(Unidad.modelo.like(f"%{modelo}%"))

        unidades = query.all()
    else:
        unidades = Unidad.query.filter_by(estado=1)
    #unidades = Unidad.query.filter(Unidad.estado != 0).all()
    return render_template('unidad/list_unidades.html', unidades=unidades)

# Reporte de unidades / buses
@main_bp.route('/report_unidades',methods=['POST'])
def report_unidad():

    outputIoStream = BytesIO()

    pdf = SimpleDocTemplate(
        outputIoStream,
        page_size=A4,
        rightMargin=12,
        leftMargin=12,
        topMargin=12,
        bottomMargin=18,
        showBoundary=True,
        )
# define estilo de tablas
    table_style = TableStyle(
            [
                ("GRID", (0, 0), (-1, -1), 0, colors.black),
                ("BOX", (0, 0), (-1, -1), 0, colors.black),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("ALIGN", (0, 0), (-1, -1), "RIGHT"),
                ("TOPPADDING", (0, 0), (-1, -1), 0),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
                ("LEFTPADDING", (0, 0), (-1, -1), 0),
                ("FONTSIZE", (0, 0), (-1, -1), 11),

app/templates/ciudad/add_ciudad.html
{% extends 'index.html' %}

{% block content %}
    <h1>Crear Ciudad</h1>
    <form action="{{ url_for('main.crear_ciudad') }}" method="post">
        <label for="nombre">Nombre:</label>
        <input type="text" id="nombre" name="nombre" required><br><br>
 
        <button class="btn btn-success" type="submit">Guardar</button>
    </form>
    <a class="btn btn-dark"  href="{{ url_for('main.list_ciudades') }}">Cancelar</a>

    {% endblock %}

app/templates/ciudad/edit_ciudad.html
{% extends 'index.html' %}

{% block content %}

<h1>Editar Ciudad</h1>
<form action="{{ url_for('main.editar_ciudad', id=ciudad.id_ciudad) }}" method="post">
    <label for="nombre">Nombre:</label>
    <input type="text" id="nombre" name="nombre" value="{{ ciudad.nombre }}" required><br><br>
 
    <button type="submit">Actualizar</button>
</form>
<a href="{{ url_for('main.list_ciudades') }}">Cancelar</a>
    {% endblock %}

app/templates/ciudad/list_ciudad.html
{% extends 'index.html' %} {% block content %}

<!-- Barra de navegación -->
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}">

<div>
  <div class="h1 fw-light text-primary">Nueva Ciudad</div>
</div>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <div class="" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a
            class="nav-link btn btn-success text-light fw-bold me-3"
            aria-current="page"
            href="{{ url_for('main.crear_ciudad') }}"
            >&#129485;Nueva Ciudad</a
          >
        </li>
        <li class="nav-item">
          <a class="nav-link btn btn-dark fw-bold text-light" href="#">&#128196;Reporte</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
<!--Cabecera de tabla de creacion de ciudades-->
<div class="container mt-5">
  <table class="table table-bordered table-hover">
    <thead class="table-light">
      <tr>
        <th scope="col">Id</th>
        <th scope="col">Nombre</th>
        <th scope="col">Estado</th>
      
      </tr>
      <!--Filtro para campos-->
      <tr>
        <th>
          <input
            type="text"
            class="filter-input tamano-1"
            id="filterid"
            placeholder="Filtrar id"
          />
        </th>
        <th>
          <input
            type="text"
            class="filter-input tamano-4"
            id="filterNombre"
            placeholder="Filtrar Nombre"
          />
        </th>

       
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
        {% for ciudad in ciudades %}
      <tr>
        <td>{{ciudad.id_ciudad}}</td>
        <td>{{ ciudad.nombre }}</td>
        <td> {{ ciudad.estado }}</td>

        <td>
          <a class="btn btn-primary" href="{{ url_for('main.editar_ciudad', id=ciudad.id_ciudad) }}">Editar</a>

        </td>
        <td>
          <form
            action="{{ url_for('main.eliminar_ciudad', id=ciudad.id_ciudad) }}"
            method="post">
            <button class="btn btn-danger" type="submit">Eliminar</button>
          </form>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}